# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'english_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(508, 174)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.file_text = QtWidgets.QLineEdit(self.centralwidget)
        self.file_text.setGeometry(QtCore.QRect(20, 60, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(16)
        self.file_text.setFont(font)
        self.file_text.setText("")
        self.file_text.setObjectName("file_text")
        self.error = QtWidgets.QLabel(self.centralwidget)
        self.error.setGeometry(QtCore.QRect(20, 120, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(16)
        self.error.setFont(font)
        self.error.setObjectName("error")
        self.finish = QtWidgets.QLabel(self.centralwidget)
        self.finish.setGeometry(QtCore.QRect(20, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(16)
        self.finish.setFont(font)
        self.finish.setObjectName("finish")
        self.choose_file = QtWidgets.QPushButton(self.centralwidget)
        self.choose_file.setGeometry(QtCore.QRect(150, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(16)
        self.choose_file.setFont(font)
        self.choose_file.setObjectName("choose_file")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(360, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(16)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.cur_num = QtWidgets.QLabel(self.centralwidget)
        self.cur_num.setGeometry(QtCore.QRect(120, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(16)
        self.cur_num.setFont(font)
        self.cur_num.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cur_num.setObjectName("cur_num")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 120, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.all_num = QtWidgets.QLabel(self.centralwidget)
        self.all_num.setGeometry(QtCore.QRect(220, 120, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(16)
        self.all_num.setFont(font)
        self.all_num.setObjectName("all_num")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "選擇 CSV 檔"))
        self.error.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#aa0000;\">發生錯誤</span></p></body></html>"))
        self.finish.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">已完成!</span></p></body></html>"))
        self.choose_file.setText(_translate("MainWindow", "選擇"))
        self.start.setText(_translate("MainWindow", "開始轉換"))
        self.cur_num.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "/"))
        self.all_num.setText(_translate("MainWindow", "0"))
